import { HttpClient, HttpRequest, HttpResponse } from "../http";
import { TaskItem, TaskList, TaskService, TaskUpdate } from "../types";
const BASE = "https://api.ticktick.com/open/v1";
export function formatTickTickDate(value: string): string { const date = value.trim(); if (/^\d{4}-\d{2}-\d{2}$/.test(date)) return `${date}T00:00:00+0000`; const noZone = date.replace(/Z$/, "+0000").replace(/([+-]\d{2}):(\d{2})$/, "$1$2"); return /[+-]\d{4}$/.test(noZone) ? noZone : `${noZone}+0000`; }
export class TickTickTaskService implements TaskService {
	readonly capabilities = { reopenTask: false, renameTaskList: true };
	constructor(private token: () => Promise<string>, private http: HttpClient, private timeZone: string, private clearToken?: () => void | Promise<void>) {}
	private async request<T>(path: string, method = "GET", body?: any): Promise<HttpResponse<T>> { const accessToken = await this.token(); const req: HttpRequest = { url: `${BASE}${path}`, method, headers: { Authorization: `Bearer ${accessToken}` } }; if (body !== undefined) { req.headers!["Content-Type"] = "application/json"; req.body = JSON.stringify(body); } const res = await this.http<T>(req); if (res.status < 200 || res.status >= 300) { if (res.status === 401 && this.clearToken) await this.clearToken(); throw new Error(this.errorFor(res.status)); } return res; }
	private errorFor(status: number) { if (status === 401) return "TickTick session expired. Connect TickTick again."; if (status === 403) return "TickTick denied task permission. Verify tasks:read and tasks:write scopes."; if (status === 404) return "TickTick task or list was not found."; if (status === 429) return "TickTick rate limit reached. Try again later."; return `TickTick request failed (${status}).`; }
	private normalize(raw: any, fallbackListId: string): TaskItem { return { id: String(raw.id), listId: String(raw.projectId || fallbackListId), title: String(raw.title || "").trim(), status: Number(raw.status) === 2 ? "completed" : "open", ...(raw.dueDate ? { dueDate: String(raw.dueDate) } : {}) }; }
	async fetchTaskLists(): Promise<TaskList[]> { const res = await this.request<any[]>("/project"); return (res.json || []).map(p => ({ id: String(p.id), title: String(p.name || "").trim() })); }
	async fetchTasks(listId: string, includeCompleted = false): Promise<TaskItem[]> { const active = await this.request<any>(`/project/${encodeURIComponent(listId)}/data`); const byId = new Map<string, TaskItem>(); for (const raw of active.json?.tasks || []) { const task = this.normalize(raw, listId); byId.set(task.id, task); } if (includeCompleted) { const completed = await this.request<any[]>("/task/completed", "POST", { projectIds: [listId] }); for (const raw of completed.json || []) { const task = this.normalize(raw, listId); const activeTask = byId.get(task.id); byId.set(task.id, activeTask ? { ...activeTask, status: "completed" } : task); } } return Array.from(byId.values()); }
	private payload(listId: string, task: TaskUpdate & { title?: string }) { const body: any = { projectId: listId }; if (task.title !== undefined) body.title = task.title; if (task.dueDate !== undefined) { body.dueDate = task.dueDate ? formatTickTickDate(task.dueDate) : null; if (task.dueDate) { body.timeZone = this.timeZone || "UTC"; body.isAllDay = true; } } return body; }
	async createTask(listId: string, task: TaskUpdate & { title: string }): Promise<TaskItem> { const res = await this.request<any>("/task", "POST", this.payload(listId, task)); return this.normalize(res.json || { ...task, projectId: listId }, listId); }
	async updateTask(listId: string, taskId: string, update: TaskUpdate): Promise<TaskItem> { const res = await this.request<any>(`/task/${encodeURIComponent(taskId)}`, "POST", { id: taskId, ...this.payload(listId, update) }); return this.normalize(res.json || { id: taskId, ...update, projectId: listId }, listId); }
	async completeTask(listId: string, taskId: string) { await this.request(`/project/${encodeURIComponent(listId)}/task/${encodeURIComponent(taskId)}/complete`, "POST"); }
	async deleteTask(listId: string, taskId: string) { await this.request(`/project/${encodeURIComponent(listId)}/task/${encodeURIComponent(taskId)}`, "DELETE"); }
	async renameTaskList(listId: string, title: string) { await this.request(`/project/${encodeURIComponent(listId)}`, "POST", { id: listId, name: title }); }
}
