name: Release Plugin

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Needed for tag lookup

            - uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - run: npm ci

            - run: npm run build

            # - name: Get Version
            #   run: echo "version=$(node -p "require('./manifest.json').version")" >> $GITHUB_OUTPUT
            #
            # - name: Commit built files
            #   run: |
            #       git config user.name "github-actions[bot]"
            #       git config user.email "github-actions[bot]@users.noreply.github.com"
            #
            #       git add main.js manifest.json versions.json
            #       git commit -m "🤖 Auto-build plugin output and bump to v${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
            #       git push
            #
            # - name: Tag release if needed
            #   run: |
            #       TAG=v${{ steps.get_version.outputs.version }}
            #       if git rev-parse "$TAG" >/dev/null 2>&1; then
            #         echo "Tag $TAG already exists, skipping."
            #       else
            #         git tag $TAG
            #         git push origin $TAG
            #         echo "Created tag: $TAG"
            #       fi
