name: Release Plugin

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # needed to get tag history

            - uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - run: npm ci

            - run: npm run build

            # Get version from manifest.json
            - id: get_version
              run: echo "version=$(node -p "require('./manifest.json').version")" >> $GITHUB_OUTPUT

            # Check if tag exists, create if not
            - name: Tag and Release
              run: |
                  VERSION=${{ steps.get_version.outputs.version }}
                  TAG=v$VERSION
                  if git rev-parse "$TAG" >/dev/null 2>&1; then
                    echo "Tag $TAG already exists, skipping."
                  else
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git tag $TAG
                    git push origin $TAG
                    echo "Created new tag: $TAG"
                  fi
