name: Build on Dev → Main Merge

on:
    push:
        branches:
            - main

jobs:
    build-on-merge:
        if: github.event.head_commit.message != '' && startsWith(github.event.head_commit.message, 'Merge pull request') && github.event.before != github.event.after
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build plugin
              run: npm run build

            - name: Upload plugin build (optional)
              uses: actions/upload-artifact@v3
              with:
                  name: obsidian-plugin
                  path: |
                      main.js
                      manifest.json
